version: "3.8"

services:
  app:
    container_name: flask_app
    build: .
    ports:
      - "${APP_PORT}:8000"
    environment:
      - DB_HOST=mysql_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    depends_on:
      - db
    networks:
      - my-network

  db:
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
